const campaignStudies = [
  {
    "brand": "Revlon",
    "tone": "#773c46",
    "category": "ECOMMERCE & DIGITAL MARKETING",
    "market": "India & Sri Lanka · 2023–Present",
    "title": "Building beauty ecommerce across markets.",
    "description": "Brand strategy, ecommerce operations and digital campaigns, with reporting automation to support execution.",
    "result": "4×",
    "metric": "ROAS · twice the prior year",
    "detail": "Launched an ecommerce website, segmented social audiences and optimized campaigns and content across Google Ads, Facebook, Instagram, Shopify, Amazon and Lazada. Coordinated budgets and agency partners. Campaign results also included 35% higher Instagram engagement.",
    "slug": "revlon",
    "goal": "Grow ecommerce sales and social engagement across India and Sri Lanka.",
    "channels": "Google Ads, Facebook, Instagram, Shopify, Amazon, Lazada"
  },
  {
    "brand": "YSL Beauty",
    "tone": "#282728",
    "category": "SEARCH & SHOPPING",
    "market": "June 2020–August 2022",
    "title": "Making search work harder for beauty.",
    "description": "Keyword, product-title and budget optimization for the L’Oréal brand across search and shopping.",
    "result": "6×",
    "metric": "return on ad spend",
    "detail": "Optimized keywords based on inventory, reallocated budgets, improved Google Shopping product titles and launched Naver Shopping campaigns. Media included Naver, Daum and network display. Provided reporting and insights to support performance optimization.",
    "slug": "ysl-beauty",
    "goal": "Maximize sales and return on advertising spend.",
    "channels": "Naver, Daum, network display, Google Shopping"
  },
  {
    "brand": "LG Business Solutions",
    "tone": "#536963",
    "category": "B2B LEAD GENERATION",
    "market": "Asia, Europe, US & Middle East · 2019–2021",
    "title": "Turning international demand into leads.",
    "description": "Multi-country Google Search and Display campaigns for B2B technology and HVAC.",
    "result": "+20%",
    "metric": "leads above target",
    "detail": "Expanded keywords and country targeting, managed country budgets and wrote ad copy. Built integrated Data Studio reporting, optimized bids and monitored search terms to improve efficiency. Delivered an automated reporting system alongside the lead-generation result.",
    "slug": "lg-business-solutions",
    "goal": "Generate qualified B2B leads while managing acquisition costs.",
    "channels": "Google Search, Google Display, Data Studio"
  },
  {
    "brand": "Massimo Dutti",
    "tone": "#b4a68d",
    "on": "#242c28",
    "category": "SEARCH & SHOPPING",
    "market": "South Korea · 2020–2022",
    "title": "Connecting global retail with local audiences.",
    "description": "Naver and Kakao campaigns with bilingual coordination between Spanish headquarters and the Korean team.",
    "result": "3×",
    "metric": "2022 sales versus 2020",
    "detail": "Managed bid optimization, proposed new ad products and monitored competitor activity. Delivered quarterly visitor analysis and competitor reports. Sales reached three times the 2020 level in 2022; this business outcome reflects more than advertising alone.",
    "slug": "massimo-dutti",
    "goal": "Support Korean retail campaigns and collaboration with Spanish headquarters.",
    "channels": "Naver, Kakao"
  },
  {
    "brand": "LG Electronics",
    "tone": "#813d39",
    "category": "GLOBAL AWARENESS / CES",
    "market": "Global markets · 2021–2022",
    "title": "Bringing a global technology moment to audiences.",
    "description": "Google and YouTube media planning for the CES 2022 campaign.",
    "result": "KPI+",
    "metric": "visitor target exceeded",
    "detail": "Planned media by country, analyzed peak viewing times and Google Analytics traffic, and optimized budgets. Segmented targeting by device, city and time. Visitor KPIs were exceeded, with CPA below the campaign benchmark.",
    "slug": "lg-electronics",
    "goal": "Drive visits and engagement for the CES campaign.",
    "channels": "Google, YouTube, Google Analytics"
  },
  {
    "brand": "Samsung SDS",
    "tone": "#445c70",
    "category": "SEARCH & DISPLAY",
    "market": "Australia, Singapore, Thailand & Philippines · Jul–Nov 2020",
    "title": "Localizing smart-home acquisition.",
    "description": "Country-specific search strategy and localized advertising for IoT and smart-home products.",
    "result": "4",
    "metric": "markets",
    "detail": "Managed and expanded keywords, reported performance and analyzed campaign data. Rebuilt keyword sets around local search trends, localized creative and reallocated budgets in real time. Campaign work improved conversions and lead acquisition while optimizing CPA.",
    "slug": "samsung-sds",
    "goal": "Generate conversions for smart-home products across four markets.",
    "channels": "Google Search, Google Display"
  },
  {
    "brand": "Farfetch",
    "tone": "#777251",
    "category": "SHOPPING ADVERTISING",
    "market": "Korea / UK headquarters collaboration · 2020–2023",
    "title": "Adapting luxury commerce for a local market.",
    "description": "Localized advertising, keyword translation and reporting across Google, Naver and Kakao.",
    "result": "3×",
    "metric": "return on ad spend",
    "detail": "Analyzed multi-country campaign performance and adapted advertising messages to local consumer behavior. Worked with headquarters to optimize performance and shared reports and insights.",
    "slug": "farfetch",
    "goal": "Grow sales efficiently through localized shopping campaigns.",
    "channels": "Google, Naver, Kakao"
  },
  {
    "brand": "Samsung / Omoomo",
    "tone": "#698896",
    "category": "APP USER ACQUISITION",
    "market": "South Korea",
    "title": "Optimizing the journey from install to engagement.",
    "description": "Acquisition campaigns for Samsung Fire & Marine Insurance and the Omoomo social platform.",
    "result": "App",
    "metric": "acquisition & retention",
    "detail": "Managed campaigns across digital and social advertising and RCPI/nCPI networks. Used audience analysis, A/B testing and funnel optimization to improve conversion, acquisition, retention and cost efficiency. Coordinated campaign execution with clients and internal teams.",
    "slug": "samsung-omoomo",
    "goal": "Improve app acquisition, conversion and retention.",
    "channels": "Digital and social advertising, RCPI/nCPI networks"
  }
];
document.querySelector('#campaign-index').innerHTML=campaignStudies.map(c=>`<a href="#${c.slug}">${c.brand} ↘</a>`).join('');
document.querySelector('#campaign-studies').innerHTML=campaignStudies.map((c,i)=>`<article class="client-feature ${i%2?'reverse':''}" id="${c.slug}"><div class="client-copy"><p class="eyebrow">0${i+1} / ${c.category}</p><h2>${c.brand}</h2><p class="client-market">${c.market}</p><ul class="campaign-summary"><li><strong>Channels:</strong> <span>${c.channels}</span></li><li><strong>Objective:</strong> <span>${c.goal}</span></li><li><strong>Scope:</strong> <span>${c.description}</span></li><li><strong>Execution:</strong> <span>${c.detail}</span></li><li><strong>Result:</strong> <span>${c.result} ${c.metric}</span></li></ul><a class="client-link" href="#${campaignStudies[(i+1)%campaignStudies.length].slug}">Next campaign <span>→</span></a></div><aside class="case-panel" style="--tone:${c.tone};--on:${c.on||'#fff'}"><p class="eyebrow">KEY PROBLEM SOLVED</p><h3>${c.title}</h3><p class="case-problem">${c.goal}</p><div class="case-divider"></div><p class="eyebrow">HOW I SOLVED IT</p><p class="case-detail">${c.detail}</p><div class="case-outcome"><div><p class="eyebrow">RESULT</p><strong>${c.result}</strong><p>${c.metric}</p></div></div></aside></article>`).join('');

