const campaigns = [
 {brand:'Revlon',tone:'#773c46',category:'ECOMMERCE & DIGITAL MARKETING',market:'India & Sri Lanka · 2023–Present',title:'Building beauty ecommerce across markets.',description:'Brand strategy, ecommerce operations and digital campaigns, with reporting automation to support execution.',result:'4×',metric:'ROAS · twice the prior year',detail:'Launched an ecommerce website, segmented social audiences and optimized campaigns and content across Google Ads, Facebook, Instagram, Shopify, Amazon and Lazada. Coordinated budgets and agency partners. The campaign portfolio also reports 35% higher Instagram engagement. These campaign-specific results have a different scope from the Umesh Modi Group figures above.'},
 {brand:'YSL Beauty',tone:'#282728',category:'SEARCH & SHOPPING',market:'June 2020–August 2022',title:'Making search work harder for beauty.',description:'Keyword, product-title and budget optimization for the L’Oréal brand across search and shopping.',result:'6×',metric:'return on ad spend',detail:'Optimized keywords based on inventory, reallocated budgets, improved Google Shopping product titles and launched Naver Shopping campaigns. Media included Naver, Daum and network display. Provided reporting and insights to support performance optimization.'},
 {brand:'LG Business Solutions',tone:'#536963',category:'B2B LEAD GENERATION',market:'Asia, Europe, US & Middle East · 2019–2021',title:'Turning international demand into leads.',description:'Multi-country Google Search and Display campaigns for B2B technology and HVAC.',result:'+20%',metric:'leads above target',detail:'Expanded keywords and country targeting, managed country budgets and wrote ad copy. Built integrated Data Studio reporting, optimized bids and monitored search terms to improve efficiency. Delivered an automated reporting system alongside the lead-generation result.'},
 {brand:'Massimo Dutti',tone:'#b4a68d',on:'#242c28',category:'SEARCH & SHOPPING',market:'South Korea · 2020–2022',title:'Connecting global retail with local audiences.',description:'Naver and Kakao campaigns with bilingual coordination between Spanish headquarters and the Korean team.',result:'3×',metric:'2022 sales versus 2020',detail:'Managed bid optimization, proposed new ad products and monitored competitor activity. Delivered quarterly visitor analysis and competitor reports. The portfolio reports sales growth during the campaign period; this is a business outcome, not a claim that advertising alone caused the increase.'},
 {brand:'LG Electronics',tone:'#813d39',category:'GLOBAL AWARENESS / CES',market:'Global markets · 2021–2022',title:'Bringing a global technology moment to audiences.',description:'Google and YouTube media planning for the CES 2022 campaign.',result:'KPI+',metric:'visitor target exceeded',detail:'Planned media by country, analyzed peak viewing times and Google Analytics traffic, and optimized budgets. Segmented targeting by device, city and time. The portfolio reports visitor KPIs exceeded and CPA below the referenced industry average; no numerical CPA is supplied.'},
 {brand:'Samsung SDS',tone:'#445c70',category:'SEARCH & DISPLAY',market:'Australia, Singapore, Thailand & Philippines · Jul–Nov 2020',title:'Localizing smart-home acquisition.',description:'Country-specific search strategy and localized advertising for IoT and smart-home products.',result:'4',metric:'markets',detail:'Managed and expanded keywords, reported performance and analyzed campaign data. Rebuilt keyword sets around local search trends, localized creative and reallocated budgets in real time. The portfolio reports improved conversions and lead acquisition with lower CPA, without numerical figures.'},
 {brand:'Farfetch',tone:'#777251',category:'SHOPPING ADVERTISING',market:'Korea / UK headquarters collaboration · 2020–2023',title:'Adapting luxury commerce for a local market.',description:'Localized advertising, keyword translation and reporting across Google, Naver and Kakao.',result:'3×',metric:'return on ad spend',detail:'Analyzed multi-country campaign performance and adapted advertising messages to local consumer behavior. Worked with headquarters to optimize performance and shared reports and insights.'},
 {brand:'Samsung / Omoomo',tone:'#698896',category:'APP USER ACQUISITION',market:'South Korea',title:'Optimizing the journey from install to engagement.',description:'Acquisition campaigns for Samsung Fire & Marine Insurance and the Omoomo social platform.',result:'App',metric:'acquisition & retention',detail:'Managed campaigns across digital and social advertising and RCPI/nCPI networks. Used audience analysis, A/B testing and funnel optimization to improve conversion, acquisition, retention and cost efficiency. Coordinated campaign execution with clients and internal teams.'}
];
const campaignSlugs = ["revlon","ysl-beauty","lg-business-solutions","massimo-dutti","lg-electronics","samsung-sds","farfetch","samsung-omoomo"];
document.querySelector('#cases').innerHTML = campaigns.map((c,i)=>`<article class="case"><div class="case-banner" style="--tone:${c.tone};--on:${c.on||'#fff'}"><span class="case-brand">${c.brand}</span><span class="case-number">0${i+1}</span></div><div class="case-body"><p class="eyebrow">${c.category}</p><p class="case-meta">${c.market}</p><h3>${c.title}</h3><p class="case-description">${c.description}</p><div class="outcome"><strong>${c.result}</strong><span>${c.metric}</span></div><a class="text-link" href="portfolio.html#${campaignSlugs[i]}">Read case study →</a></div></article>`).join('');
const jobs=[
 ['MAR 2023–PRESENT','Singapore','Umesh Modi Group','Digital Marketing & Ecommerce Manager',['Led ecommerce growth across South Asian markets, contributing to 200% YoY revenue growth while maintaining ROAS above 500%.','Planned integrated digital campaigns, increasing social media engagement by 20% YoY.','Developed automated reporting with Google Sheets and Google Apps Script, and supported demand forecasting, inventory planning and product availability.','Worked with sales, operations, payment, advertising and fulfillment partners; used generative AI to support content and workflow optimization.']],
 ['NOV 2022–MAR 2023','Seoul, South Korea','Incross','Performance Marketing Manager',['Managed campaigns for Samsung Fire & Marine Insurance and Omoomo across digital, social and RCPI/nCPI networks.','Used performance data and audience insights to optimize conversion, acquisition, retention and cost efficiency, coordinating with clients and internal teams.']],
 ['AUG 2019–NOV 2022','Seoul, South Korea','JBridge Marketing Company','Performance Marketing Manager',['Managed campaigns and client communications for L’Oréal, Massimo Dutti, LG Electronics, Oracle and Samsung SDS.','Developed channel strategies, managed budgets and surpassed lead-generation targets through forecasting, audience targeting and budget allocation.','Presented insights and strategic recommendations; led RFPs, client proposals and campaign planning for multiple brands.']],
 ['AUG 2018–JUL 2019','Daejeon, South Korea','Natural History Research Institute','Marketing Manager',['Managed international partners, distributors, market research, negotiations and contracts for science education products.','Presented education systems to government representatives in Liberia and delivered digital-education presentations at a Samsung Electronics-hosted seminar for the Taiwanese Ministry of Education.','Developed school-specific strategies, pricing and product configurations, and delivered teacher training.']],
 ['JAN–AUG 2018','Daejeon, South Korea','KORAD','Marketing Manager',['Supported international business development for broadcasting software through market research, demonstrations and partner negotiations.','Managed partner relationships, customer consultations, MOUs, contracts and export documentation.']],
 ['JUN–NOV 2014','Delhi, India','Khaitan & Khaitan','Law Associate',['Drafted legal documents and contracts, researched legal matters, prepared opinion notes and contributed to litigation strategy.','Developed an Excel-based CRM to support client relationship management.']]
];
document.querySelector('#jobs').innerHTML=jobs.map(j=>`<article class="job"><div><span class="date">${j[0]}</span><span class="job-location">${j[1]}</span></div><div><h3>${j[2]}</h3><h4>${j[3]}</h4><ul>${j[4].map(t=>`<li>${t}</li>`).join('')}</ul></div></article>`).join('');
document.querySelector('#year').textContent=new Date().getFullYear();
